services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=netline_reader
      - POSTGRES_PASSWORD=netline_secret
      - POSTGRES_USER=netline
    ports:
      - '5432:5432'
